# Algorithm Parameters
alpha: 0.001
gamma: 0.8
epsilon: 0.99
epsilon_discount: 0.001
epsilon_min: 0.01
batch_size: 128
tao: 10
nepisodes: 800

# Environment Parameters
limits: # in meters
  min_x: -70.0
  max_x: 70.0
  min_y: -5.0
  max_y: 45.0
base:
  x: 0
  y: 0
  z: 5

running_step: 1.5  # in seconds
battery_depletion: 2.0 # in each 2 seconds